import { Component } from '@angular/core';
import { IonicModule } from '@ionic/angular';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-tab2',
  standalone: true,
  imports: [IonicModule, CommonModule],
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss']
})
export class Tab2Page {
  pastQuotes: string[] = [
    'Believe you can and you’re halfway there.',
    'Small steps every day.',
    'Dream big. Start small. Act now.',
    'Keep going.',
    'Make it happen.',
    'Create your own sunshine.',
    'Choose joy.',
    'You’ve got this.',
    'Do something today your future self will thank you for.',
    'Success is a series of small wins.',
    'Rise and shine.',
    'Focus on what matters.',
    'Failure is part of the plan.',
    'Just start.',
    'Be your own hero.',
    'Good things take time.',
    'One day or day one—you decide.',
    'Hustle in silence.',
    'Turn “I wish” into “I will.”',
    'Dreams don’t work unless you do.',
    'Stay hungry. Stay humble.',
    'Your only limit is you.',
    'Push yourself, no one else will.',
    'Believe in the process.',
    'Make progress, not excuses.',
    'Action cures fear.',
    'Doubt kills more dreams than failure.',
    'Focus on the step, not the whole staircase.',
    'Keep your eyes on the prize.',
    'Success starts with self‑discipline.',
    'Never be afraid to try.',
    'Better an oops than a what‑if.',
    'The secret of getting ahead is getting started.',
    'Your vibe attracts your tribe.',
    'Consistency is key.',
    'Everything is figure‑out‑able.',
    'You are stronger than you think.',
    'Work until you no longer have to introduce yourself.',
    'Courage over comfort.',
    'Start where you are. Use what you have.',
    'Do it with passion or not at all.',
    'Stay focused and extra sparkly.',
    'Success is the sum of small efforts.',
    'Think it. Want it. Get it.',
    'Great things never come from comfort zones.',
    'Turn setbacks into comebacks.',
    'Stay patient and trust your journey.',
    'Prove yourself to yourself, not others.',
    'Lose the excuses.',
    'Nothing changes if nothing changes.',
    'Refuse to be ordinary.',
    'Your pace is perfect.',
    'Every day is a fresh start.',
    'Quality over quantity.',
    'Discipline equals freedom.',
    'Work hard in silence, let success speak.',
    'Dream. Plan. Do.',
    'Be the energy you want to attract.',
    'Finish what you started.',
    'Wake up with purpose.',
    'Success is momentum.',
    'You were born to be real, not perfect.',
    'Fail forward.',
    'Grow through what you go through.',
    'Be brave enough to begin.',
    'Fortune favors the bold.',
    'Perseverance pays off.',
    'Mindset is everything.',
    'Storms make trees take deeper roots.',
    'Today is another chance.',
    'Grind now. Shine later.',
    'Nothing worth having comes easy.',
    'Stay curious.',
    'Make your future self proud.',
    'Work smart and hard.',
    'Turn pressure into power.',
    'Fall seven times, stand up eight.',
    'Focus equals success.',
    'Leap and the net will appear.',
    'Earned, not given.',
    'Your effort matters.',
    'Dreams demand hustle.',
    'Success is a habit.',
    'Think big, start small.',
    'Never stop learning.',
    'Impossible is just an opinion.',
    'Keep the main thing the main thing.',
    'Practice breeds progress.',
    'The best time is now.',
    'Trust the timing.',
    'Go the extra mile—it’s never crowded.',
    'Stay grounded. Aim high.',
    'Win the morning, win the day.',
    'Be stubborn about goals, flexible about methods.',
    'Challenge equals change.',
    'Move with purpose.',
    'Results happen over time, not overnight.',
    'Stay relentless.',
    'Your dream job doesn’t exist—create it.'
  ];
}
